# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af8c89fd7d2050e94589de3fcf0b8b1319c51048e4c4f47151c7ec19f437f62d6c6e6fdcc416573d8daab7393e0e8db6b274c9e54ccddffb04c746e2a78e28d3

test:
  secret_key_base: 0e04975635a8589b03bc8687ff44650a3b24d55bf16c9694edfbd7f8c5f6dde5e7a1cce1410ab8117316b22a976acfb2bca702164b61e3711db5b5eb4a76b1c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
